project: 
  type: website
  output-dir: docs
  
website: 
  site-url: https://janlorenz.github.io/summerbreakcovid
  repo-url: https://github.com/janlorenz/summerbreakcovid
  repo-actions: [edit, issue]